name: 'Deploy to Cloud Run (Staging)'

on:
    push:
        branches:
            - prod-release
jobs:
    build:
        name: Cloud Run Deployment
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Setup GCP Service Account
              uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
              with:
                  version: 'latest'
                  service_account_email: ${{ secrets.GCP_SA_EMAIL }}
                  service_account_key: ${{ secrets.GCP_SA_KEY }}
                  export_default_credentials: true

            - name: Configure Docker
              run: |
                  gcloud auth configure-docker

            - name: Build
              run: |
                  docker build -f ./docker/stag.Dockerfile . -t asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCR_IMAGE_NAME_PROD }} --build-arg GIT_ACCESS_TOKEN_CURL_CONFIG=${{ secrets.GIT_ACCESS_TOKEN_CURL_CONFIG }}

            - name: Push
              run: |
                  docker push asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCR_IMAGE_NAME_PROD }}:latest

            - name: Deploy
              run: |
                  gcloud run deploy ${{ secrets.GCP_CLOUDRUN_SRV_NAME_PROD }} \
                  --region ${{ secrets.GCP_REGION }} \
                  --image asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCR_IMAGE_NAME_PROD }} \
                  --platform managed \
                  --allow-unauthenticated \
                  --project ${{ secrets.GCP_PROJECT_ID }}
