name: 'Push Image (Staging)'

on:
    push:
        branches:
            - stag-release-image
jobs:
    build:
        name: Cloud Run Deployment
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Setup GCP Service Account
              uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
              with:
                  version: 'latest'
                  service_account_email: ${{ secrets.GCP_SA_EMAIL }}
                  service_account_key: ${{ secrets.GCP_SA_KEY }}
                  export_default_credentials: true

            - name: Configure Docker
              run: |
                  gcloud auth configure-docker

            - name: Build
              run: |
                  docker build -f ./docker/stag.Dockerfile . -t asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCR_IMAGE_NAME }} --build-arg GIT_ACCESS_TOKEN_CURL_CONFIG=${{ secrets.GIT_ACCESS_TOKEN_CURL_CONFIG }}

            - name: Push
              run: |
                  docker push asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCR_IMAGE_NAME }}:latest
